### PR TITLE
remove import of syslog on windows platforms

### PR DESCRIPTION
**Pull request by beliaev-maksim**

### CODE REVIEW

**Comment by beliaev-maksim** [comment]
@Carreau 
can you please check the PR and release a new version once merged?

`velin` will require this change on Win machines

**Comment by beliaev-maksim** [comment]
@Carreau any update?

**Comment by Carreau** [comment]
Thanks, apologies, the last few weeks have been hectic.

**Comment by Carreau** [comment]
And released.

**Comment by beliaev-maksim** [comment]
Thanks!

**Pull request merged**
